version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=todo_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 5