name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
       
  build:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: SonarQube Backend Scan
#      uses: kitabisa/sonarqube-action@v1.2.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/main/frontend/package-lock.json

    - name: Install Dependencies
      working-directory: src/main/frontend
      run: npm install

    - name: Build
      working-directory: src/main/frontend
      run: npm run build --if-present

#    - name: Test
#      working-directory: src/main/frontend
#      run: npm test

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload entire repository
        path: 'src/main/frontend/build/.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2